---
- name: Create Frappe User
  user:
    name: frappe
    password: "!"
    password_lock: yes
    shell: /bin/bash
    append: no
    uid: 1000
    generate_ssh_key: yes

- name: Allow Passwordless sudo Access to Frappe User
  copy:
    src: files/sudoers
    dest: /etc/sudoers.d/frappe

- name: Create SSH Keys for root User
  user:
    name: root
    generate_ssh_key: yes
