- targets:
    - "{{ item.name }}"
  labels:
    job: node
    __metrics_path__: /metrics/node

- targets:
    - "{{ item.name }}"
  labels:
    job: nginx
    __metrics_path__: /metrics/nginx

- targets:
    - "{{ item.name }}"
  labels:
    job: elasticsearch
    __metrics_path__: /metrics/elasticsearch
