---
- name: Create MySQL Exporter Systemd Service File
  template:
    src: ../../mysqld_exporter/templates/mysqld_exporter.service
    dest: /etc/systemd/system/mysqld_exporter.service
    owner: root
    group: root
    mode: 0644

- name: Restart MySQL Exporter Service
  systemd:
    daemon_reload: true
    name: mysqld_exporter
    enabled: yes
    state: restarted
